# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UptbmvXOIkfJauLiWuBmFwbCl0TLkhTG
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from sklearn.base import BaseEstimator, TransformerMixin


class IQRCapper(BaseEstimator, TransformerMixin):

    def fit(self, X, y=None):
        X = np.asarray(X, dtype=float)

        q1 = np.nanpercentile(X, 25, axis=0)
        q3 = np.nanpercentile(X, 75, axis=0)

        iqr = q3 - q1

        self.lower = q1 - 1.5 * iqr
        self.upper = q3 + 1.5 * iqr

        return self

    def transform(self, X):
        X = np.asarray(X, dtype=float)

        return np.clip(
            X,
            self.lower,
            self.upper
        )

pipeline = joblib.load("models/stroke_pipeline.pkl")

st.title("🧠 Stroke Prediction")
st.write("Enter patient information to predict stroke risk.")

age = st.number_input(
    "Age",
    min_value=0.0,
    max_value=100.0,
    value=45.0
)

gender = st.selectbox(
    "Gender",
    ["Male", "Female", "Other"]
)

hypertension = st.selectbox(
    "Hypertension",
    [0, 1]
)

heart_disease = st.selectbox(
    "Heart Disease",
    [0, 1]
)

ever_married = st.selectbox(
    "Ever Married",
    ["Yes", "No"]
)

work_type = st.selectbox(
    "Work Type",
    [
        "Private",
        "Self-employed",
        "Govt_job",
        "children",
        "Never_worked"
    ]
)

residence_type = st.selectbox(
    "Residence Type",
    ["Urban", "Rural"]
)

avg_glucose_level = st.number_input(
    "Average Glucose Level",
    min_value=0.0,
    value=100.0
)

bmi = st.number_input(
    "BMI",
    min_value=0.0,
    max_value=100.0,
    value=25.0
)

smoking_status = st.selectbox(
    "Smoking Status",
    [
        "formerly smoked",
        "never smoked",
        "smokes",
        "Unknown"
    ]
)


if st.button("Predict Stroke Risk"):

    input_data = pd.DataFrame({
        "age": [age],
        "gender": [gender],
        "hypertension": [hypertension],
        "heart_disease": [heart_disease],
        "ever_married": [ever_married],
        "work_type": [work_type],
        "Residence_type": [residence_type],
        "avg_glucose_level": [avg_glucose_level],
        "bmi": [bmi],
        "smoking_status": [smoking_status]
    })

    prediction = pipeline.predict(input_data)[0]
    probability = pipeline.predict_proba(input_data)[0][1]

    if prediction == 1:
        st.error(
            f"Higher predicted stroke risk: "
            f"{probability * 100:.2f}%"
        )
    else:
        st.success(
            f"Lower predicted stroke risk: "
            f"{probability * 100:.2f}%"
        )